### ISSUE TITLE
`SCALE_FACTOR` does not take into account `1e36` and quote/base token decimals

### ISSUE THREAD

**Issue by MerlinEgalite** [0xValJohn/morpho-blue-oracles#1]
https://github.com/0xValJohn/morpho-blue-oracles/blob/99f3b8a61b4ab65254352f8a4e53c44944e70992/src/TricryptoLpOracle.sol#L48

See here:
https://github.com/morpho-org/morpho-blue-oracles/blob/5bca61d0c4650fd5dae0a757c3d4789ec0d9febb/src/ChainlinkOracle.sol#L116

As mentioned in the TG chat, I think reusing the `ChainlinkOracle` contract avoid those kind of issues as all computations are performed inside and there's less chance to make mistakes

**Comment by Jean-Grimal** [comment]
It doesn't take into account base and quote token decimals. Is it because it is enforced that they always have the same decimals ?

**Comment by 0xValJohn** [comment]
Addressed in https://github.com/0xValJohn/morpho-blue-oracles/commit/a6ba1d9f53a7714a5ce43a7ae50f992becdd2d2e
