### ISSUE TITLE
Useless handling of lido logic

### ISSUE THREAD

**Issue by MerlinEgalite** [0xValJohn/morpho-blue-oracles#2]
If you want to use market pricing you can reuse this oracle deployed by Compound: https://etherscan.io/address/0x4F67e4d9BD67eFa28236013288737D39AeF48e79#readContract

It's CL compliant so you don't need to add this logic and could just reuse the feed

**Comment by 0xValJohn** [comment]
Removed in https://github.com/0xValJohn/morpho-blue-oracles/commit/a6ba1d9f53a7714a5ce43a7ae50f992becdd2d2e
