### ISSUE TITLE
`_crvusdFeed` could be immutable in `TricryptoLpOracleFactory `

### ISSUE THREAD

**Issue by Jean-Grimal** [0xValJohn/morpho-blue-oracles#4]
If the only crvUsd feed used is the crvUsd/usd feed, I guess `_crvusdFeed` can be an immutable variable for the `TricryptoLpOracleFactory` contract.
Will the crvUsd/eth feed be used ? I feel like that all crvUsd collateral token have chainlink usd feeds, so we can manage to always use the crvUsd/usd feed

**Comment by 0xValJohn** [comment]
Made immutable in https://github.com/0xValJohn/morpho-blue-oracles/commit/a6ba1d9f53a7714a5ce43a7ae50f992becdd2d2e

**Comment by Jean-Grimal** [comment]
I would also have the decimals of `_crvusdFeed` immutable, and include it in the computation of `SCALE_FACTOR`

**Comment by 0xValJohn** [comment]
Changes made here: https://github.com/0xValJohn/morpho-blue-oracles/commit/ba6ae9f1dda69d2826d60b1efea207003045d1b8
